dist: xenial # for mysql

# For Selenium, need geckodriver
env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

language: python

python:
  - "3.6"

install:
  - 'pip install pipenv'
  - 'pipenv sync'
  - pipenv install coveralls

script:

  - python purbeurre/manage.py migrate
  - pytest purbeurre/

after_success:
  - coveralls