@startuml 02_uc_products
title Diagrame de cas d'utilisation "Products"

package Products{
    left to right direction
    (Faire une recherche) as SEARCH
    (Choisir un produit) as SELECT_PRODUCT
    (Trouver un substitut) as FIND_SUBST
    (Enregistrer un substitut) AS SET_SUBST
    (Afficher un produit) AS SHOW_PRODUCT
    (Supprimer un substitut) AS DEL_SUBST
    (Consulter "Mes produits") as SHOW_FAV
    (Consulter les substituts enregistrés) as SHOW_SUBST
    (Récupérer les données de OFF) as SNIFFER

}

actor user
actor OpenFoofFacts <<system>>
actor Developpeur

user -- SEARCH
user -- SELECT_PRODUCT
user -- FIND_SUBST
user -- SHOW_PRODUCT
user -- SET_SUBST
user -- DEL_SUBST
user -- SHOW_FAV
user -- SHOW_SUBST
SNIFFER -- OpenFoofFacts
Developpeur -- SNIFFER

@enduml