@startuml 02_uc_authentication
title Diagramme de cas d'utilisation *Authentication*

package Authentication{
    left to right direction
    (Créer un compte) as CREATE
    (Se connecter) as LOGIN
    (Se déconnecter) as LOGOUT
}

actor user

user -- CREATE
user -- LOGIN
user -- LOGOUT


@enduml