@startuml 03_activity

start
if (est ce que la DB existe?) then(non)
    :Creer la base;
    :remplir la DB;
else (oui)
endif
:Page d'intro;
if (que voulez vous faire ?) then (choisir un substitut)
    :Choisir une catégorie;
    :Choisir un produit + indiquer le grade + pagination;
    :Choisir du substitut + indiquer le grade + pagination;
else (consulter la liste des substituts)
    :Liste des Substituts enregistrés;
endif
:Détail Substitut + enregistrer/supprimer;

@enduml