@startuml 03_activity_03
title Workflow suppression d'un substitut

|utilisateur|
|systeme|


|utilisateur|
start
:se connecte;
|systeme|
:active la session;
|utilisateur|
:clique sur [mes produits];
|systeme|
:Affiche la liste de produits enregistré (initial);
|utilisateur|
:Sélectionne un produit (initial);
|systeme|
:Affiche la liste de produits 
enregistrés (substituts);
|utilisateur|
:supprime le substitut
(clique sur l'icone [supprimer]);
|systeme|
:supprime la conbinaison
initial/substitut;
:change l'icone [supprimer] par l'icone [enregistrer];
end


@enduml