@startuml 04_deployment

node "Appareil\n utilisateur"{
    component navigateur
}

node "Appareil\nDeveloppeur"{
    component Terminal
}

cloud Heroku{
    ' left to right direction
    database Postgres
    rectangle Gunicorn{
        component Django
    }
    component Static
}

Django -- Postgres
Django -- Static

cloud OpenFoodFacts{
    component API
}

navigateur - Django : "HTTPS"
Terminal -- Django : "SSH"
Django - API : "HTTPS"

@enduml