# Generated by Django 2.2 on 2019-04-13 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('nutrition_grades', models.CharField(max_length=1)),
                ('fat', models.CharField(max_length=8)),
                ('fat_100g', models.DecimalField(decimal_places=1, max_digits=3)),
                ('saturated_fat', models.CharField(max_length=8)),
                ('saturated_fat_100g', models.DecimalField(decimal_places=1, max_digits=3)),
                ('sugars', models.CharField(max_length=8)),
                ('sugars_100g', models.DecimalField(decimal_places=1, max_digits=3)),
                ('salt', models.CharField(max_length=8)),
                ('salt_100g', models.DecimalField(decimal_places=1, max_digits=3)),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.Product')),
                ('substitute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='products.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product_id', 'substitute_id', 'user_id')},
            },
        ),
    ]
